name: Release Package

on:
  push:
    tags:
      - "[0-9]*.[0-9]*"
      - "v[0-9]*.[0-9]*"

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - uses: tinkerer-red/GML-Actions/actions/package@v2
        with:
          project-file: "Tome/Tome.yyp"
          package-id: "Tome"
          include-folders: "Tome"
          package-name: "Tome"
          package-publisher: "CataclysmicStudios"
          append-version-to-filename: "true"
          project-tool-version: "2024.14.160"
          gmpm-registry: "https://gmpm.gamemaker.io"
